package apigraph

import (
	"errors"
	"strings"
	"testing"

	"github.com/graphql-go/graphql"

	"github.com/ziyan/teanode/internal/api"
)

// The schema is generated by reflection when the server starts, so a type
// the generator cannot translate — a map, a pointer to an input struct — is
// found by the first person to run the binary rather than by the compiler.
// Building it here moves that to the test run.
func TestSchemaBuilds(t *testing.T) {
	t.Parallel()

	component, err := New(nil, nil, nil, nil, nil, nil, nil, nil, &api.Settings{})
	if err != nil {
		t.Fatalf("the schema does not build: %s", err)
	}
	schema := component.(*graph).schema

	// The operations this change added, with the argument types it gave
	// them. Asking the schema rather than the Go types, because the Go
	// types are what the generator reads and the schema is what it wrote.
	for operation, wanted := range map[string][]string{
		"SendMail":       {"domainId", "messageParameters"},
		"RenderTemplate": {"domainId", "templateId", "templateParameters", "locale", "variables"},
		"RenderLayout":   {"domainId", "layoutParameters", "locale", "variables"},
	} {
		field := schema.QueryType().Fields()[operation]
		if field == nil {
			field = schema.MutationType().Fields()[operation]
		}
		if field == nil {
			t.Errorf("%s is not in the schema", operation)
			continue
		}
		have := map[string]bool{}
		for _, argument := range field.Args {
			have[argument.Name()] = true
		}
		for _, name := range wanted {
			if !have[name] {
				t.Errorf("%s has no argument %q", operation, name)
			}
		}
	}

	// Every field of DomainParameters has to be optional, because an update
	// sends the one setting it is changing.
	//
	// The name was not, so the generator made it String! — and the schema
	// then refused any update that did not carry the domain name, before the
	// resolver saw it. Saving the mail server names from the dashboard, and
	// moving the signing selector, both failed that way, and the failure
	// looked to the operator like a button that did nothing.
	for name, field := range schema.Type("DomainParametersInput").(*graphql.InputObject).Fields() {
		if strings.HasSuffix(field.Type.String(), "!") {
			t.Errorf("domainParameters.%s is %s; a required field makes every partial update fail",
				name, field.Type)
		}
	}

	// A message's attachments carry bytes, which travel as base64 through
	// the Data scalar. If the generator ever stops recognising []byte the
	// field would silently become a list of Any.
	message := schema.Type("MessageParametersInput").(*graphql.InputObject)
	attachments := message.Fields()["attachments"].Type.String()
	if !strings.Contains(attachments, "AttachmentParametersInput") {
		t.Errorf("attachments is %s, expected a list of AttachmentParametersInput", attachments)
	}
	attachment := schema.Type("AttachmentParametersInput").(*graphql.InputObject)
	if content := attachment.Fields()["content"].Type.String(); content != "Data!" {
		t.Errorf("attachment content is %s, expected Data!", content)
	}
}

func TestValidateLocales(t *testing.T) {
	t.Parallel()

	for name, testCase := range map[string]struct {
		defaultLocale string
		locales       []string
		ok            bool
	}{
		"nothing":             {"", nil, true},
		"defaultOnly":         {"en", nil, true},
		"translations":        {"en", []string{"zh-CN", "ja"}, true},
		"badDefault":          {"English", nil, false},
		"badTranslation":      {"en", []string{"zh CN"}, false},
		"repeatedDifferently": {"en", []string{"zh-CN", "zh_cn"}, false},
		"sameAsDefault":       {"en", []string{"EN"}, false},
	} {
		testCase := testCase
		t.Run(name, func(t *testing.T) {
			t.Parallel()
			err := validateLocales(testCase.defaultLocale, testCase.locales)
			if (err == nil) != testCase.ok {
				t.Fatalf("expected ok=%v, got %v", testCase.ok, err)
			}
			if err != nil && !errors.Is(err, api.ErrInvalidArguments) {
				t.Errorf("expected an invalid arguments error, got %v", err)
			}
		})
	}
}

func TestParseAddresses(t *testing.T) {
	t.Parallel()

	addresses, err := parseAddresses([]string{"a@example.com", " ", "Somebody <b@example.net>"})
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}
	if strings.Join(addresses, ",") != "a@example.com,b@example.net" {
		t.Errorf("unexpected addresses %v", addresses)
	}
	if _, err := parseAddresses([]string{"not an address"}); !errors.Is(err, api.ErrInvalidArguments) {
		t.Errorf("expected an invalid arguments error, got %v", err)
	}
}
